### ISSUE TITLE
Request for docs clarifications / guidance

### ISSUE THREAD

**Issue by mgravell** [Azure/trusted-signing-action#10]
Context: I'm an experience library developer who knows exactly zero (on a good day) about the machinery of code-signing, hence my libraries are not currently signed; "if only there was a MSFT service that could help me with this?!"

So: I have (after some stumbles) successfully created a Trusted Signing certificate profile in Azure; next step:"now let's sign something" - find this supported GitHub Action, and see:

``` yaml
      - name: Sign files with Trusted Signing
        uses: azure/trusted-signing-action@v0.3.15
        with:
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
```

ELI5; if we assume that a Trusted Signing certificate profile exists in an Azure account accessible to the user, how do I get from *there* to *here*? What CLIENT_ID and CLIENT_SECRET is it asking me for, and where would I find and/or generate them? The docs right now assume a lot of information that is probably obvious when you've done it at least once, but which is unfamiliar if you're coming in cold. Unfortunately the "learn" docs stop at the point when a certificate profile exists, and just [waves vaguely](https://learn.microsoft.com/en-us/azure/trusted-signing/how-to-signing-integrations#use-other-signing-integrations-with-trusted-signing) in the direction of "oh, and you might want to use it with GitHub Actions", without saying how.
