### ISSUE TITLE
Feature Request: Add files-recurse-limit Parameter to Control Recursive Signing

### ISSUE THREAD

**Issue by mamogh** [Azure/trusted-signing-action#52]
I’d like to suggest adding a files-recurse-limit parameter. Since the signing service incurs costs per signature, allowing users to set a limit (e.g., 200 files) on recursive signing operations would help prevent unexpected large bills. This feature would enable better cost management by restricting the number of files processed, ensuring that signing actions remain within budget.

```yaml
uses: Azure/trusted-signing-action
with:
  files-recurse-limit: 200
```

Maybe just a files-limit. Also would be nice if i could see in the log how many singing i have used or remaining.
