### ISSUE TITLE
Integrate with Azure Login

### ISSUE THREAD

**Issue by wsugarman** [Azure/trusted-signing-action#66]
I appreciate all of the authentication options in the action that are presumably provided by the [`DefaultAzureCredential`](https://github.com/Azure/azure-sdk-for-net/blob/524d441c0263d1b8a525de320512ceebe62c8014/sdk/identity/Azure.Identity/src/Credentials/DefaultAzureCredential.cs). But I also think it chafes with the other Azure GitHub actions like [Azure CLI](https://github.com/marketplace/actions/azure-cli-action), [Azure PowerShell](https://github.com/marketplace/actions/azure-powershell-action), [ARM Template Deploy](https://github.com/marketplace/actions/deploy-azure-resource-manager-arm-template), and [Azure Web App Deploy](https://github.com/marketplace/actions/azure-webapp). All of these instead rely on [Azure Login](https://github.com/marketplace/actions/azure-login) to authenticate.

I think it would simplify the action to simply remove the various `exclude*` parameters and rely entirely on Azure Login for the authentication:
```yaml
steps:
  - name: Azure login
    uses: azure/login@v2
    with:
      client-id: ${{ secrets.AZURE_CLIENT_ID }}
      tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  - name: Sign files with Trusted Signing
    uses: azure/trusted-signing-action@v0.5.1
    with:
      endpoint: https://eus.codesigning.azure.net/
      trusted-signing-account-name: vscx-codesigning
      certificate-profile-name: vscx-certificate-profile
      files-folder: ${{ github.workspace }}\App\App\bin\Release\net8.0-windows
      files-folder-filter: exe,dll
      file-digest: SHA256
      timestamp-rfc3161: http://timestamp.acs.microsoft.com
      timestamp-digest: SHA256
```

**Comment by bgrainger** [comment]
Agreed; I also find the current setup unnecessarily verbose because I don't know (in a CI scenario) when I would ever use anything else. Making Azure Login the expected way to use this action makes sense to me.

Currently, I have to write out the following block of YAML in every workflow that uses Trusted Signing (to be able to efficiently use Azure Login):

```yaml
with:
  exclude-azure-cli-credential: false
  exclude-environment-credential: true
  exclude-workload-identity-credential: true
  exclude-managed-identity-credential: true
  exclude-shared-token-cache-credential: true
  exclude-visual-studio-credential: true
  exclude-visual-studio-code-credential: true
  exclude-azure-powershell-credential: true
  exclude-azure-developer-cli-credential: true
  exclude-interactive-browser-credential: true
```

**Comment by japarson** [comment]
@wsugarman @bgrainger I think this makes a lot of sense, but I'm a little bit unclear about how the internal `DeafultAzureToken` should be handled in this scenario. In this case, would the only credential allowed be the `azure-cli-credential`?

**Comment by bgrainger** [comment]
Yes; you would basically replace `new DefaultAzureCredential()` with `new AzureCliCredential()`.

See a similar change I made in (a forked version of) `dotnet sign`: https://github.com/Faithlife/sign/commit/2bac0c2dfc32efae64dea1d8aac6678c57c360e1

**Comment by wsugarman** [comment]
@japarson - Yeah, it'd be exactly as @bgrainger described. Those other Azure actions are mostly using the Azure CLI to perform their logic, so they implicitly rely upon az cli being authenticated ahead of time. Start with using [`AzureCliCredential`](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.azureclicredential?view=azure-dotnet). In the future, you could always add something like Azure PowerShell auth via [`ChainedTokenCredential`](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.chainedtokencredential?view=azure-dotnet).

**Comment by japarson** [comment]
This action is a wrapper around the Trusted Signing powershell module which is itself a wrapper around a library which uses DeafultAzureCredential. We can't directly switch to `AzureCliCredential` as the module supports other authentication methods like interactive for example.

Would it be an OK compromise to instead exclude all methods except for azure cli by default?

It would use these values by default and you could still alter them if you wish, but anyone using Azure Login wouldn't need to use these inputs at all.
```yaml
with:
  exclude-azure-cli-credential: false
  exclude-environment-credential: true
  exclude-workload-identity-credential: true
  exclude-managed-identity-credential: true
  exclude-shared-token-cache-credential: true
  exclude-visual-studio-credential: true
  exclude-visual-studio-code-credential: true
  exclude-azure-powershell-credential: true
  exclude-azure-developer-cli-credential: true
  exclude-interactive-browser-credential: true
```
