### ISSUE TITLE
Feature Request: Separate setup-trusted-signing action

### ISSUE THREAD

**Issue by oliversaggau** [Azure/trusted-signing-action#69]
We have a bigger project solution that build a multi-module application and also builds various WiX .msi projects and WiX bundles where the output of the dependencies of course needs to already be signed before building the dependant setup. Currently we simply use `msbuild solution.sln ...` to build everything in our GitHub pipeline, and it would be tedious to split up this process into multiple steps (phases), including/excluding different projects each time and use the `azure/trusted-signing-action` in between.

So instead we decided to use the Trusted Signing PowerShell module as an MSBuild task, so we could simply have MSBuild sign the files. For this we of course still need to install the module and of course we also want to cache the dependencies, just like `azure/trusted-signing-action` does. So we basically copied the first steps from `azure/trusted-signing-action` and created our own `setup-trusted-signing` like this (based on the current https://github.com/Azure/trusted-signing-action/blob/0d74250c661747df006298d0fb49944c10f16e03/action.yml)
```
name: 'Setup Trusted Signing'
description: 'Setup Trusted Signing.'

inputs:
  cache-dependencies:
    description: A boolean value (true/false) that indicates if the dependencies for this action should be cached
                 by GitHub or not. The default value is true. When using self-hosted runners, caches from workflow
                 runs are stored on GitHub-owned cloud storage. A customer-owned storage solution is only available
                 with GitHub Enterprise Server. When enabled, this option can reduce the duration of the action by
                 at least 1 minute.
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Set variables
      id: set-variables
      shell: 'pwsh'
      run: |
        $defaultPath = $env:PSModulePath -split ';' | Select-Object -First 1
        "PSMODULEPATH=$defaultPath" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
        
        "TRUSTED_SIGNING_MODULE_VERSION=0.5.3" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
        "BUILD_TOOLS_NUGET_VERSION=10.0.22621.3233" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
        "TRUSTED_SIGNING_NUGET_VERSION=1.0.53" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
        "DOTNET_SIGNCLI_NUGET_VERSION=0.9.1-beta.24469.1" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

    - name: Cache TrustedSigning PowerShell module
      id: cache-module
      uses: actions/cache@v4
      env:
        cache-name: cache-module
      with:
        path: ${{ steps.set-variables.outputs.PSMODULEPATH }}\TrustedSigning\${{ steps.set-variables.outputs.TRUSTED_SIGNING_MODULE_VERSION }}
        key: TrustedSigning-${{ steps.set-variables.outputs.TRUSTED_SIGNING_MODULE_VERSION }}
      if: ${{ inputs.cache-dependencies == 'true' }}
  
    - name: Cache Microsoft.Windows.SDK.BuildTools NuGet package
      id: cache-buildtools
      uses: actions/cache@v4
      env:
        cache-name: cache-buildtools
      with:
        path: ~\AppData\Local\TrustedSigning\Microsoft.Windows.SDK.BuildTools\Microsoft.Windows.SDK.BuildTools.${{ steps.set-variables.outputs.BUILD_TOOLS_NUGET_VERSION }}
        key: Microsoft.Windows.SDK.BuildTools-${{ steps.set-variables.outputs.BUILD_TOOLS_NUGET_VERSION }}
      if: ${{ inputs.cache-dependencies == 'true' }}

    - name: Cache Microsoft.Trusted.Signing.Client NuGet package
      id: cache-tsclient
      uses: actions/cache@v4
      env:
        cache-name: cache-tsclient
      with:
        path: ~\AppData\Local\TrustedSigning\Microsoft.Trusted.Signing.Client\Microsoft.Trusted.Signing.Client.${{ steps.set-variables.outputs.TRUSTED_SIGNING_NUGET_VERSION }}
        key: Microsoft.Trusted.Signing.Client-${{ steps.set-variables.outputs.TRUSTED_SIGNING_NUGET_VERSION }}
      if: ${{ inputs.cache-dependencies == 'true' }}

    - name: Cache SignCli NuGet package
      id: cache-signcli
      uses: actions/cache@v4
      env:
        cache-name: cache-signcli
      with:
        path: ~\AppData\Local\TrustedSigning\sign\sign.${{ steps.set-variables.outputs.DOTNET_SIGNCLI_NUGET_VERSION }}
        key: SignCli-${{ steps.set-variables.outputs.DOTNET_SIGNCLI_NUGET_VERSION }}
      if: ${{ inputs.cache-dependencies == 'true' }}

    - name: Install Trusted Signing module
      shell: 'pwsh'
      run: |
        Install-Module -Name TrustedSigning -RequiredVersion ${{ steps.set-variables.outputs.TRUSTED_SIGNING_MODULE_VERSION }} -Force -Repository PSGallery
      if: ${{ inputs.cache-dependencies != 'true' || steps.cache-module.outputs.cache-hit != 'true' }}
```
But copying the code of course requires us to manually track and merge updates from your code base. So it would be awesome if you could split up your action into two actions `azure/setup-trusted-signing` and `azure/trusted-signing-action` (which then internally uses `azure/setup-trusted-signing`) so others (like us) could also separately only use `azure/setup-trusted-signing`
