### ISSUE TITLE
BUG: Trusted-signing-account-name Marked as Optional but Causes Failure if Missing

### ISSUE THREAD

**Issue by ShimaMichael** [Azure/trusted-signing-action#74]
The trusted-signing-account-name input in the Azure Trusted Signing GitHub Action is marked as not required, but the script throws an error if it is missing, unless the deprecated code-signing-account-name is provided. This creates confusing behaviour, as users expect optional inputs to not be mandatory.
###Current behaviour
``` yml
inputs:
  trusted-signing-account-name:
    description: "The Trusted Signing Account name."
    required: false
```
However, in the PowerShell script, an exception is thrown if neither trusted-signing-account-name nor code-signing-account-name is set:
```sh
$trustedSigningAccountName = "${{ inputs.trusted-signing-account-name }}"

if ([string]::IsNullOrWhiteSpace($trustedSigningAccountName)) {
    $trustedSigningAccountName = "${{ inputs.code-signing-account-name }}"
    
    if (-Not [string]::IsNullOrWhiteSpace($trustedSigningAccountName)) {
        Write-Warning "The 'code-signing-account-name' input is deprecated. Please use 'trusted-signing-account-name' instead."
    } else {
        throw "The 'trusted-signing-account-name' input is required."
    }
}
```
###Sample run
```yml
name: "Sign Application"
description: "Signs the application with the certificate"
runs:
    using: "composite"
    steps:
      - name: Sign Application with azure trusted signing
        uses: azure/trusted-signing-action@v0.5.1
        with: 
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }} 
          azure-client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          endpoint: ${{ secrets.AZURE_ENDPOINT }}   
          files-folder-filter: exe
          timetamp-rfc3161: http://timestamp.digicert.com
          timestamp-digest: SHA256
```
will output:
```stdout
Exception: D:\a\_temp\01a98b58-8014-4d8b-89dc-6a835d221b82.ps1:15
Line |
  15 |      throw "The 'trusted-signing-account-name' input is required."
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The 'trusted-signing-account-name' input is required.
Error: Process completed with exit code 1.
```

This created some confusion when trying to use the tool and caused unexpected build errors. Should trusted-signing-account-name be explicitly marked as required, or is there a scenario where neither is needed?
